config-version: 1.5
#---------------------
#logging levels: 0 normal, 1 finer, -1 reduced
logging-level: 0
#the maximum sequential time an async operation should halt the server
#in milliseconds
async-max-halt-time: 10

#how many ticks to wait till next sync operation
async-tick-delay: 3

#how many threads should be running parallely ( typically the number of cores )
max-running-threads: default


