name: RegionalPathfinder
main: com.mattymatty.RegionalPathfinder.RegionalPathfinder
version: 0.8.5 - Merged - Test15
author: The__Matty
api-version: 1.13
load: STARTUP

commands:
  regionalpathfinder:
    description: default command for handling PathRegions
    usage: /regionalpathfinder
    aliases: [rpf,rph]
    permission: rpf.test
    permission-message: You don't have <permission>

permissions:
  rpf.test:
    description: allows usage of test commands
    default: false
  rpf.*:
    description: allows usage of test commands
    default: false
    children:
      rpf.test: true